name: Tests

on:
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build library
        run: npm run build

      - name: Run unit tests
        run: npm run test:coverage
